### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by howardroark2018** [umomega/bookkeeper#1]
Tested it on my server. Really great work, and very good UI. It's clean, simple and feels nice to use. I think it has a great future ahead if new features are added continuously. As this is just the start and is at alpha state, I obviously didn't expect many features, yet whatever features it does have, are good. Hope to see many more critical features coming up next. 

PS: Your sense of design and simplicity is really appreciable. Keep up the work!

**Comment by Hyleeh** [comment]
Many thanks for your complements, it feels great to be appreciated like so.

I will try to add as many features I can in the future but this is a one-man project that will hopefully become something that is supported and extended by the community.

So feel free to open some issue for suggestions or even pull requests, would be really happy to see that.

I recently published the documentation here so feel free to check that out as well: https://umomega.github.io/bookkeeper-docs/

Best,
