### ISSUE TITLE
Theme Problem

### ISSUE THREAD

**Issue by tarrel** [umomega/bookkeeper#2]
Hello , As far as I have seen the functionality is very very good.
But I have a problem with theme.
It is displaying plain HTML and CSS is not loading.

How to install theme ?

Kind regards and Congrats.

**Comment by Hyleeh** [comment]
Hi, thank you :)

I think I need more information, do you have screenshots? Have you changed the public directory?

The common problem for that is when you change the public directory the themes config should also be updated under config/themes.php

Let me know

Best regards,

**Comment by tarrel** [comment]
I have not changed nothing.

![image](https://user-images.githubusercontent.com/28483286/50634923-6f436980-0f50-11e9-9736-621906cc7a79.png)
Here is the public directory.

And in config/themes.php : 
![image](https://user-images.githubusercontent.com/28483286/50634997-c0535d80-0f50-11e9-9b7d-c4bbab726dc0.png)
![image](https://user-images.githubusercontent.com/28483286/50635003-c6e1d500-0f50-11e9-8313-46b8e2b2d470.png)

Kind regards.

**Comment by tarrel** [comment]
When I open with:
`php artisan serve` - the install process starts with theme with "localhost:8000". 
But when I finish install to go to auth/login it shows : 
> The requested URL was not found on this server.

redirects to route "localhost/auth/login".
![image](https://user-images.githubusercontent.com/28483286/50637352-fcd78700-0f59-11e9-8e06-a0bfb9efdb73.png)

I have changed the base route but nothing has changed for theme .

**Comment by Hyleeh** [comment]
That mog

**Comment by Hyleeh** [comment]
I see, I never tested bookkeeper with artisan serve

I will try and will let you know

In the meanwhile you can try adding the port number to the .env file explicitely under the APP_URL variable and run php artisan optimize again to register correctly. The theme package uses the base url variable

**Comment by Hyleeh** [comment]
Hi again,

I just tested it with the artisan development server.

You need to enter the base url as `http://localhost:8000` during installation.
If you do not want to reinstall bookkeeper, just go to `.env` file and change the `APP_URL` variable to `http://localhost:8000` and then use the `php artisan optimize` command to register the config.

After that point your browser to `http://localhost:8000` which will automatically redirect you to the login page.

Be sure to use the latest version as I have added new features recently.

Let me know if you encounter any other issues and feel free to drop a start and suggest new features.

Best,

**Comment by tarrel** [comment]
It works like a charm.
Please can I send you an email .
I want to contribute in this project as much as I can .

**Comment by Hyleeh** [comment]
Happy to hear that!

I would prefer if you would open issues about suggestions or create some PR's for contribution

But you can send me mails at info@umomega.com, the public address for my company

Best,
